#!/usr/bin/env bash
set -euo pipefail

scripts/generate-kaitai

for grammar_src in tools/*/src/parser.c; do
  [ -e "${grammar_src}" ] || continue
  grammar_dir=$(dirname "$(dirname "${grammar_src}")")
  cc -shared -fPIC -I "${grammar_dir}/src" "${grammar_src}" -o "${grammar_dir}/parser.so"
done

ruff check .
PYLINTHOME=.pylint.d pylint src tests
mypy --strict src tests
bandit -c bandit.yaml -r src

shellcheck scripts/*

radon cc src tests --json --show-complexity > radon-complexity.json
scripts/check-radon-complexity radon-complexity.json 4

ruff format --check src tests
pytest
