/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 65
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 42
#define ALIAS_COUNT 0
#define TOKEN_COUNT 22
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 11
#define MAX_ALIAS_SEQUENCE_LENGTH 9
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 10
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LT_DASH = 1,
  anon_sym_LPAREN = 2,
  anon_sym_AMP = 3,
  anon_sym_RPAREN = 4,
  anon_sym_PIPE = 5,
  anon_sym_poll = 6,
  anon_sym_until = 7,
  anon_sym_EQ_EQ = 8,
  anon_sym_call = 9,
  anon_sym_stall = 10,
  anon_sym_info = 11,
  anon_sym_smbus_execute = 12,
  anon_sym_COMMA = 13,
  anon_sym_mem = 14,
  anon_sym_LBRACK = 15,
  anon_sym_RBRACK = 16,
  anon_sym_io = 17,
  anon_sym_pci = 18,
  anon_sym_COLON = 19,
  sym_hex_number = 20,
  sym_meta_variable = 21,
  sym_source_file = 22,
  sym__statement = 23,
  sym_assignment_statement = 24,
  sym_read_write_statement = 25,
  sym_poll_statement = 26,
  sym_call_statement = 27,
  sym_call_context_statement = 28,
  sym_stall_statement = 29,
  sym_info_statement = 30,
  sym_smbus_statement = 31,
  sym_target = 32,
  sym_argument_list = 33,
  sym_target_mem = 34,
  sym_target_io = 35,
  sym_target_pci = 36,
  sym_pci_location = 37,
  sym_address = 38,
  sym_value = 39,
  aux_sym_source_file_repeat1 = 40,
  aux_sym_argument_list_repeat1 = 41,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LT_DASH] = "<-",
  [anon_sym_LPAREN] = "(",
  [anon_sym_AMP] = "&",
  [anon_sym_RPAREN] = ")",
  [anon_sym_PIPE] = "|",
  [anon_sym_poll] = "poll",
  [anon_sym_until] = "until",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_call] = "call",
  [anon_sym_stall] = "stall",
  [anon_sym_info] = "info",
  [anon_sym_smbus_execute] = "smbus_execute",
  [anon_sym_COMMA] = ",",
  [anon_sym_mem] = "mem",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_io] = "io",
  [anon_sym_pci] = "pci",
  [anon_sym_COLON] = ":",
  [sym_hex_number] = "hex_number",
  [sym_meta_variable] = "meta_variable",
  [sym_source_file] = "source_file",
  [sym__statement] = "_statement",
  [sym_assignment_statement] = "assignment_statement",
  [sym_read_write_statement] = "read_write_statement",
  [sym_poll_statement] = "poll_statement",
  [sym_call_statement] = "call_statement",
  [sym_call_context_statement] = "call_context_statement",
  [sym_stall_statement] = "stall_statement",
  [sym_info_statement] = "info_statement",
  [sym_smbus_statement] = "smbus_statement",
  [sym_target] = "target",
  [sym_argument_list] = "argument_list",
  [sym_target_mem] = "target_mem",
  [sym_target_io] = "target_io",
  [sym_target_pci] = "target_pci",
  [sym_pci_location] = "pci_location",
  [sym_address] = "address",
  [sym_value] = "value",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_argument_list_repeat1] = "argument_list_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LT_DASH] = anon_sym_LT_DASH,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_AMP] = anon_sym_AMP,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_poll] = anon_sym_poll,
  [anon_sym_until] = anon_sym_until,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_call] = anon_sym_call,
  [anon_sym_stall] = anon_sym_stall,
  [anon_sym_info] = anon_sym_info,
  [anon_sym_smbus_execute] = anon_sym_smbus_execute,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_mem] = anon_sym_mem,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_io] = anon_sym_io,
  [anon_sym_pci] = anon_sym_pci,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_hex_number] = sym_hex_number,
  [sym_meta_variable] = sym_meta_variable,
  [sym_source_file] = sym_source_file,
  [sym__statement] = sym__statement,
  [sym_assignment_statement] = sym_assignment_statement,
  [sym_read_write_statement] = sym_read_write_statement,
  [sym_poll_statement] = sym_poll_statement,
  [sym_call_statement] = sym_call_statement,
  [sym_call_context_statement] = sym_call_context_statement,
  [sym_stall_statement] = sym_stall_statement,
  [sym_info_statement] = sym_info_statement,
  [sym_smbus_statement] = sym_smbus_statement,
  [sym_target] = sym_target,
  [sym_argument_list] = sym_argument_list,
  [sym_target_mem] = sym_target_mem,
  [sym_target_io] = sym_target_io,
  [sym_target_pci] = sym_target_pci,
  [sym_pci_location] = sym_pci_location,
  [sym_address] = sym_address,
  [sym_value] = sym_value,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_argument_list_repeat1] = aux_sym_argument_list_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LT_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_poll] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_until] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_call] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_stall] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_info] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_smbus_execute] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_mem] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_io] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_pci] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_hex_number] = {
    .visible = true,
    .named = true,
  },
  [sym_meta_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_assignment_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_read_write_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_poll_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_call_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_call_context_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_stall_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_info_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_smbus_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_target] = {
    .visible = true,
    .named = true,
  },
  [sym_argument_list] = {
    .visible = true,
    .named = true,
  },
  [sym_target_mem] = {
    .visible = true,
    .named = true,
  },
  [sym_target_io] = {
    .visible = true,
    .named = true,
  },
  [sym_target_pci] = {
    .visible = true,
    .named = true,
  },
  [sym_pci_location] = {
    .visible = true,
    .named = true,
  },
  [sym_address] = {
    .visible = true,
    .named = true,
  },
  [sym_value] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_argument_list_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_address = 1,
  field_context = 2,
  field_data = 3,
  field_data_mask = 4,
  field_duration = 5,
  field_entry_point = 6,
  field_information = 7,
  field_segment = 8,
  field_source = 9,
  field_target = 10,
  field_value = 11,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_address] = "address",
  [field_context] = "context",
  [field_data] = "data",
  [field_data_mask] = "data_mask",
  [field_duration] = "duration",
  [field_entry_point] = "entry_point",
  [field_information] = "information",
  [field_segment] = "segment",
  [field_source] = "source",
  [field_target] = "target",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 1},
  [4] = {.index = 4, .length = 1},
  [5] = {.index = 5, .length = 1},
  [6] = {.index = 6, .length = 2},
  [7] = {.index = 8, .length = 2},
  [8] = {.index = 10, .length = 3},
  [9] = {.index = 13, .length = 4},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_entry_point, 1},
  [1] =
    {field_target, 0},
    {field_value, 2},
  [3] =
    {field_duration, 2},
  [4] =
    {field_information, 2},
  [5] =
    {field_address, 2},
  [6] =
    {field_context, 3},
    {field_entry_point, 1},
  [8] =
    {field_address, 2},
    {field_segment, 0},
  [10] =
    {field_data, 8},
    {field_data_mask, 5},
    {field_target, 3},
  [13] =
    {field_data, 8},
    {field_data_mask, 5},
    {field_source, 3},
    {field_target, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(37);
      ADVANCE_MAP(
        '&', 40,
        '(', 39,
        ')', 41,
        ',', 50,
        '0', 34,
        ':', 56,
        '<', 2,
        '=', 3,
        '[', 52,
        ']', 53,
        'c', 5,
        'i', 26,
        'm', 10,
        'p', 8,
        's', 24,
        'u', 27,
        '|', 42,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == '(') ADVANCE(39);
      if (lookahead == ')') ADVANCE(41);
      if (lookahead == '0') ADVANCE(34);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (lookahead == '$' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 2:
      if (lookahead == '-') ADVANCE(38);
      END_STATE();
    case 3:
      if (lookahead == '=') ADVANCE(45);
      END_STATE();
    case 4:
      if (lookahead == '_') ADVANCE(13);
      END_STATE();
    case 5:
      if (lookahead == 'a') ADVANCE(21);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(23);
      END_STATE();
    case 7:
      if (lookahead == 'b') ADVANCE(32);
      END_STATE();
    case 8:
      if (lookahead == 'c') ADVANCE(15);
      if (lookahead == 'o') ADVANCE(22);
      END_STATE();
    case 9:
      if (lookahead == 'c') ADVANCE(33);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(25);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(9);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(49);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(35);
      END_STATE();
    case 14:
      if (lookahead == 'f') ADVANCE(28);
      END_STATE();
    case 15:
      if (lookahead == 'i') ADVANCE(55);
      END_STATE();
    case 16:
      if (lookahead == 'i') ADVANCE(20);
      END_STATE();
    case 17:
      if (lookahead == 'l') ADVANCE(46);
      END_STATE();
    case 18:
      if (lookahead == 'l') ADVANCE(43);
      END_STATE();
    case 19:
      if (lookahead == 'l') ADVANCE(47);
      END_STATE();
    case 20:
      if (lookahead == 'l') ADVANCE(44);
      END_STATE();
    case 21:
      if (lookahead == 'l') ADVANCE(17);
      END_STATE();
    case 22:
      if (lookahead == 'l') ADVANCE(18);
      END_STATE();
    case 23:
      if (lookahead == 'l') ADVANCE(19);
      END_STATE();
    case 24:
      if (lookahead == 'm') ADVANCE(7);
      if (lookahead == 't') ADVANCE(6);
      END_STATE();
    case 25:
      if (lookahead == 'm') ADVANCE(51);
      END_STATE();
    case 26:
      if (lookahead == 'n') ADVANCE(14);
      if (lookahead == 'o') ADVANCE(54);
      END_STATE();
    case 27:
      if (lookahead == 'n') ADVANCE(30);
      END_STATE();
    case 28:
      if (lookahead == 'o') ADVANCE(48);
      END_STATE();
    case 29:
      if (lookahead == 's') ADVANCE(4);
      END_STATE();
    case 30:
      if (lookahead == 't') ADVANCE(16);
      END_STATE();
    case 31:
      if (lookahead == 't') ADVANCE(12);
      END_STATE();
    case 32:
      if (lookahead == 'u') ADVANCE(29);
      END_STATE();
    case 33:
      if (lookahead == 'u') ADVANCE(31);
      END_STATE();
    case 34:
      if (lookahead == 'x') ADVANCE(36);
      END_STATE();
    case 35:
      if (lookahead == 'x') ADVANCE(11);
      END_STATE();
    case 36:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(57);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_LT_DASH);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_AMP);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_poll);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_until);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_call);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_stall);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_info);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_smbus_execute);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_mem);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_io);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_pci);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_hex_number);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(57);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_meta_variable);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 1},
  [33] = {.lex_state = 1},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LT_DASH] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_AMP] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_poll] = ACTIONS(1),
    [anon_sym_until] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_call] = ACTIONS(1),
    [anon_sym_stall] = ACTIONS(1),
    [anon_sym_info] = ACTIONS(1),
    [anon_sym_smbus_execute] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_mem] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_io] = ACTIONS(1),
    [anon_sym_pci] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [sym_hex_number] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(45),
    [sym__statement] = STATE(3),
    [sym_assignment_statement] = STATE(3),
    [sym_read_write_statement] = STATE(3),
    [sym_poll_statement] = STATE(3),
    [sym_call_statement] = STATE(3),
    [sym_call_context_statement] = STATE(3),
    [sym_stall_statement] = STATE(3),
    [sym_info_statement] = STATE(3),
    [sym_smbus_statement] = STATE(3),
    [sym_target] = STATE(44),
    [sym_target_mem] = STATE(38),
    [sym_target_io] = STATE(38),
    [sym_target_pci] = STATE(38),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_poll] = ACTIONS(5),
    [anon_sym_call] = ACTIONS(7),
    [anon_sym_stall] = ACTIONS(9),
    [anon_sym_info] = ACTIONS(11),
    [anon_sym_smbus_execute] = ACTIONS(13),
    [anon_sym_mem] = ACTIONS(15),
    [anon_sym_io] = ACTIONS(17),
    [anon_sym_pci] = ACTIONS(19),
  },
  [STATE(2)] = {
    [sym__statement] = STATE(2),
    [sym_assignment_statement] = STATE(2),
    [sym_read_write_statement] = STATE(2),
    [sym_poll_statement] = STATE(2),
    [sym_call_statement] = STATE(2),
    [sym_call_context_statement] = STATE(2),
    [sym_stall_statement] = STATE(2),
    [sym_info_statement] = STATE(2),
    [sym_smbus_statement] = STATE(2),
    [sym_target] = STATE(44),
    [sym_target_mem] = STATE(38),
    [sym_target_io] = STATE(38),
    [sym_target_pci] = STATE(38),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(21),
    [anon_sym_poll] = ACTIONS(23),
    [anon_sym_call] = ACTIONS(26),
    [anon_sym_stall] = ACTIONS(29),
    [anon_sym_info] = ACTIONS(32),
    [anon_sym_smbus_execute] = ACTIONS(35),
    [anon_sym_mem] = ACTIONS(38),
    [anon_sym_io] = ACTIONS(41),
    [anon_sym_pci] = ACTIONS(44),
  },
  [STATE(3)] = {
    [sym__statement] = STATE(2),
    [sym_assignment_statement] = STATE(2),
    [sym_read_write_statement] = STATE(2),
    [sym_poll_statement] = STATE(2),
    [sym_call_statement] = STATE(2),
    [sym_call_context_statement] = STATE(2),
    [sym_stall_statement] = STATE(2),
    [sym_info_statement] = STATE(2),
    [sym_smbus_statement] = STATE(2),
    [sym_target] = STATE(44),
    [sym_target_mem] = STATE(38),
    [sym_target_io] = STATE(38),
    [sym_target_pci] = STATE(38),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(47),
    [anon_sym_poll] = ACTIONS(5),
    [anon_sym_call] = ACTIONS(7),
    [anon_sym_stall] = ACTIONS(9),
    [anon_sym_info] = ACTIONS(11),
    [anon_sym_smbus_execute] = ACTIONS(13),
    [anon_sym_mem] = ACTIONS(15),
    [anon_sym_io] = ACTIONS(17),
    [anon_sym_pci] = ACTIONS(19),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 1,
    ACTIONS(49), 12,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_poll,
      anon_sym_call,
      anon_sym_stall,
      anon_sym_info,
      anon_sym_smbus_execute,
      anon_sym_COMMA,
      anon_sym_mem,
      anon_sym_io,
      anon_sym_pci,
  [15] = 2,
    ACTIONS(53), 1,
      anon_sym_LPAREN,
    ACTIONS(51), 9,
      ts_builtin_sym_end,
      anon_sym_poll,
      anon_sym_call,
      anon_sym_stall,
      anon_sym_info,
      anon_sym_smbus_execute,
      anon_sym_mem,
      anon_sym_io,
      anon_sym_pci,
  [30] = 1,
    ACTIONS(55), 9,
      ts_builtin_sym_end,
      anon_sym_poll,
      anon_sym_call,
      anon_sym_stall,
      anon_sym_info,
      anon_sym_smbus_execute,
      anon_sym_mem,
      anon_sym_io,
      anon_sym_pci,
  [42] = 1,
    ACTIONS(57), 9,
      ts_builtin_sym_end,
      anon_sym_poll,
      anon_sym_call,
      anon_sym_stall,
      anon_sym_info,
      anon_sym_smbus_execute,
      anon_sym_mem,
      anon_sym_io,
      anon_sym_pci,
  [54] = 1,
    ACTIONS(59), 9,
      ts_builtin_sym_end,
      anon_sym_poll,
      anon_sym_call,
      anon_sym_stall,
      anon_sym_info,
      anon_sym_smbus_execute,
      anon_sym_mem,
      anon_sym_io,
      anon_sym_pci,
  [66] = 1,
    ACTIONS(61), 9,
      ts_builtin_sym_end,
      anon_sym_poll,
      anon_sym_call,
      anon_sym_stall,
      anon_sym_info,
      anon_sym_smbus_execute,
      anon_sym_mem,
      anon_sym_io,
      anon_sym_pci,
  [78] = 1,
    ACTIONS(63), 9,
      ts_builtin_sym_end,
      anon_sym_poll,
      anon_sym_call,
      anon_sym_stall,
      anon_sym_info,
      anon_sym_smbus_execute,
      anon_sym_mem,
      anon_sym_io,
      anon_sym_pci,
  [90] = 1,
    ACTIONS(65), 9,
      ts_builtin_sym_end,
      anon_sym_poll,
      anon_sym_call,
      anon_sym_stall,
      anon_sym_info,
      anon_sym_smbus_execute,
      anon_sym_mem,
      anon_sym_io,
      anon_sym_pci,
  [102] = 1,
    ACTIONS(67), 9,
      ts_builtin_sym_end,
      anon_sym_poll,
      anon_sym_call,
      anon_sym_stall,
      anon_sym_info,
      anon_sym_smbus_execute,
      anon_sym_mem,
      anon_sym_io,
      anon_sym_pci,
  [114] = 1,
    ACTIONS(69), 9,
      ts_builtin_sym_end,
      anon_sym_poll,
      anon_sym_call,
      anon_sym_stall,
      anon_sym_info,
      anon_sym_smbus_execute,
      anon_sym_mem,
      anon_sym_io,
      anon_sym_pci,
  [126] = 5,
    ACTIONS(15), 1,
      anon_sym_mem,
    ACTIONS(17), 1,
      anon_sym_io,
    ACTIONS(19), 1,
      anon_sym_pci,
    STATE(41), 1,
      sym_target,
    STATE(38), 3,
      sym_target_mem,
      sym_target_io,
      sym_target_pci,
  [144] = 5,
    ACTIONS(15), 1,
      anon_sym_mem,
    ACTIONS(17), 1,
      anon_sym_io,
    ACTIONS(19), 1,
      anon_sym_pci,
    STATE(51), 1,
      sym_target,
    STATE(38), 3,
      sym_target_mem,
      sym_target_io,
      sym_target_pci,
  [162] = 4,
    ACTIONS(71), 1,
      anon_sym_RPAREN,
    STATE(22), 1,
      sym_value,
    STATE(56), 1,
      sym_argument_list,
    ACTIONS(73), 2,
      sym_hex_number,
      sym_meta_variable,
  [176] = 3,
    STATE(36), 1,
      sym_address,
    STATE(49), 1,
      sym_pci_location,
    ACTIONS(75), 2,
      sym_hex_number,
      sym_meta_variable,
  [187] = 3,
    ACTIONS(77), 1,
      anon_sym_LPAREN,
    STATE(8), 1,
      sym_value,
    ACTIONS(73), 2,
      sym_hex_number,
      sym_meta_variable,
  [198] = 3,
    ACTIONS(79), 1,
      anon_sym_RPAREN,
    ACTIONS(81), 1,
      anon_sym_COMMA,
    STATE(19), 1,
      aux_sym_argument_list_repeat1,
  [208] = 2,
    STATE(5), 1,
      sym_value,
    ACTIONS(73), 2,
      sym_hex_number,
      sym_meta_variable,
  [216] = 2,
    STATE(53), 1,
      sym_value,
    ACTIONS(73), 2,
      sym_hex_number,
      sym_meta_variable,
  [224] = 3,
    ACTIONS(84), 1,
      anon_sym_RPAREN,
    ACTIONS(86), 1,
      anon_sym_COMMA,
    STATE(24), 1,
      aux_sym_argument_list_repeat1,
  [234] = 2,
    STATE(40), 1,
      sym_value,
    ACTIONS(73), 2,
      sym_hex_number,
      sym_meta_variable,
  [242] = 3,
    ACTIONS(86), 1,
      anon_sym_COMMA,
    ACTIONS(88), 1,
      anon_sym_RPAREN,
    STATE(19), 1,
      aux_sym_argument_list_repeat1,
  [252] = 2,
    STATE(55), 1,
      sym_address,
    ACTIONS(75), 2,
      sym_hex_number,
      sym_meta_variable,
  [260] = 2,
    STATE(57), 1,
      sym_value,
    ACTIONS(73), 2,
      sym_hex_number,
      sym_meta_variable,
  [268] = 2,
    STATE(52), 1,
      sym_value,
    ACTIONS(73), 2,
      sym_hex_number,
      sym_meta_variable,
  [276] = 2,
    STATE(63), 1,
      sym_address,
    ACTIONS(75), 2,
      sym_hex_number,
      sym_meta_variable,
  [284] = 2,
    STATE(58), 1,
      sym_value,
    ACTIONS(73), 2,
      sym_hex_number,
      sym_meta_variable,
  [292] = 2,
    STATE(13), 1,
      sym_value,
    ACTIONS(73), 2,
      sym_hex_number,
      sym_meta_variable,
  [300] = 2,
    STATE(6), 1,
      sym_value,
    ACTIONS(73), 2,
      sym_hex_number,
      sym_meta_variable,
  [308] = 2,
    STATE(64), 1,
      sym_address,
    ACTIONS(75), 2,
      sym_hex_number,
      sym_meta_variable,
  [316] = 2,
    STATE(48), 1,
      sym_value,
    ACTIONS(73), 2,
      sym_hex_number,
      sym_meta_variable,
  [324] = 1,
    ACTIONS(90), 2,
      anon_sym_RBRACK,
      anon_sym_COLON,
  [329] = 1,
    ACTIONS(92), 2,
      anon_sym_LT_DASH,
      anon_sym_AMP,
  [334] = 2,
    ACTIONS(94), 1,
      anon_sym_RBRACK,
    ACTIONS(96), 1,
      anon_sym_COLON,
  [341] = 1,
    ACTIONS(98), 2,
      anon_sym_LT_DASH,
      anon_sym_AMP,
  [346] = 1,
    ACTIONS(100), 2,
      anon_sym_LT_DASH,
      anon_sym_AMP,
  [351] = 1,
    ACTIONS(102), 2,
      anon_sym_LT_DASH,
      anon_sym_AMP,
  [356] = 1,
    ACTIONS(79), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [361] = 1,
    ACTIONS(104), 1,
      anon_sym_AMP,
  [365] = 1,
    ACTIONS(106), 1,
      anon_sym_LBRACK,
  [369] = 1,
    ACTIONS(108), 1,
      anon_sym_LBRACK,
  [373] = 1,
    ACTIONS(110), 1,
      anon_sym_LT_DASH,
  [377] = 1,
    ACTIONS(112), 1,
      ts_builtin_sym_end,
  [381] = 1,
    ACTIONS(114), 1,
      anon_sym_until,
  [385] = 1,
    ACTIONS(116), 1,
      anon_sym_LPAREN,
  [389] = 1,
    ACTIONS(118), 1,
      anon_sym_RPAREN,
  [393] = 1,
    ACTIONS(120), 1,
      anon_sym_RBRACK,
  [397] = 1,
    ACTIONS(122), 1,
      anon_sym_LPAREN,
  [401] = 1,
    ACTIONS(124), 1,
      anon_sym_AMP,
  [405] = 1,
    ACTIONS(126), 1,
      anon_sym_RPAREN,
  [409] = 1,
    ACTIONS(128), 1,
      anon_sym_RPAREN,
  [413] = 1,
    ACTIONS(130), 1,
      anon_sym_LPAREN,
  [417] = 1,
    ACTIONS(132), 1,
      anon_sym_RBRACK,
  [421] = 1,
    ACTIONS(134), 1,
      anon_sym_RPAREN,
  [425] = 1,
    ACTIONS(136), 1,
      anon_sym_RPAREN,
  [429] = 1,
    ACTIONS(138), 1,
      anon_sym_RPAREN,
  [433] = 1,
    ACTIONS(140), 1,
      anon_sym_EQ_EQ,
  [437] = 1,
    ACTIONS(142), 1,
      anon_sym_PIPE,
  [441] = 1,
    ACTIONS(144), 1,
      anon_sym_LPAREN,
  [445] = 1,
    ACTIONS(146), 1,
      anon_sym_LBRACK,
  [449] = 1,
    ACTIONS(148), 1,
      anon_sym_RBRACK,
  [453] = 1,
    ACTIONS(150), 1,
      anon_sym_RBRACK,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 15,
  [SMALL_STATE(6)] = 30,
  [SMALL_STATE(7)] = 42,
  [SMALL_STATE(8)] = 54,
  [SMALL_STATE(9)] = 66,
  [SMALL_STATE(10)] = 78,
  [SMALL_STATE(11)] = 90,
  [SMALL_STATE(12)] = 102,
  [SMALL_STATE(13)] = 114,
  [SMALL_STATE(14)] = 126,
  [SMALL_STATE(15)] = 144,
  [SMALL_STATE(16)] = 162,
  [SMALL_STATE(17)] = 176,
  [SMALL_STATE(18)] = 187,
  [SMALL_STATE(19)] = 198,
  [SMALL_STATE(20)] = 208,
  [SMALL_STATE(21)] = 216,
  [SMALL_STATE(22)] = 224,
  [SMALL_STATE(23)] = 234,
  [SMALL_STATE(24)] = 242,
  [SMALL_STATE(25)] = 252,
  [SMALL_STATE(26)] = 260,
  [SMALL_STATE(27)] = 268,
  [SMALL_STATE(28)] = 276,
  [SMALL_STATE(29)] = 284,
  [SMALL_STATE(30)] = 292,
  [SMALL_STATE(31)] = 300,
  [SMALL_STATE(32)] = 308,
  [SMALL_STATE(33)] = 316,
  [SMALL_STATE(34)] = 324,
  [SMALL_STATE(35)] = 329,
  [SMALL_STATE(36)] = 334,
  [SMALL_STATE(37)] = 341,
  [SMALL_STATE(38)] = 346,
  [SMALL_STATE(39)] = 351,
  [SMALL_STATE(40)] = 356,
  [SMALL_STATE(41)] = 361,
  [SMALL_STATE(42)] = 365,
  [SMALL_STATE(43)] = 369,
  [SMALL_STATE(44)] = 373,
  [SMALL_STATE(45)] = 377,
  [SMALL_STATE(46)] = 381,
  [SMALL_STATE(47)] = 385,
  [SMALL_STATE(48)] = 389,
  [SMALL_STATE(49)] = 393,
  [SMALL_STATE(50)] = 397,
  [SMALL_STATE(51)] = 401,
  [SMALL_STATE(52)] = 405,
  [SMALL_STATE(53)] = 409,
  [SMALL_STATE(54)] = 413,
  [SMALL_STATE(55)] = 417,
  [SMALL_STATE(56)] = 421,
  [SMALL_STATE(57)] = 425,
  [SMALL_STATE(58)] = 429,
  [SMALL_STATE(59)] = 433,
  [SMALL_STATE(60)] = 437,
  [SMALL_STATE(61)] = 441,
  [SMALL_STATE(62)] = 445,
  [SMALL_STATE(63)] = 449,
  [SMALL_STATE(64)] = 453,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(46),
  [26] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(50),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(54),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(61),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(62),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(42),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value, 1, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call_statement, 2, 0, 1),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_read_write_statement, 9, 0, 9),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_smbus_statement, 3, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment_statement, 3, 0, 2),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_info_statement, 4, 0, 4),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_smbus_statement, 4, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_stall_statement, 4, 0, 3),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call_context_statement, 5, 0, 6),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_poll_statement, 9, 0, 8),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2, 0, 0),
  [81] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 1, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 2, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_address, 1, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_target_io, 4, 0, 5),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pci_location, 1, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_target_mem, 4, 0, 5),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_target, 1, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_target_pci, 4, 0, 5),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [112] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pci_location, 3, 0, 7),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_s3boot_semantic(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "s3boot_semantic",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
